version: '3'
services:

  react:
    build: ./frontend
    ports:
      - "3000:3000"

  node:
    build: ./backend/node
    ports:
      - "5000:5000"
    environment:
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_HOST: postgres
    depends_on:
      - postgres
    volumes:
      - ./backend/node:/usr/src/app
    working_dir: /usr/src/app
    command: sh -c "node scripts/db-schema-setup.js && npm start"

  python:
    build: ./backend/python
    ports:
      - "5001:5001"

  postgres:
    image: postgres:14
    container_name: postgres_db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    driver: local