server:
  port: 5000
  url: "http://0.0.0.0:5001"

database:
  url: "mongodb://localhost:27017/dbname"

auth:
  jwtSecret: "jwt_secret"

logging:
  level: "info"

rateLimiter:
  windowMs: 900000 
  max: 100

cors:
  origin: "*"
