name: Build and Test CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build React Frontend
        run: |
          docker build -t react-frontend ./app/frontend

      - name: Test Run React Frontend
        run: |
          docker run -d --name react-app -p 3000:3000 react-frontend
          sleep 10 
          # Perform tests here, e.g., curl localhost:3000
          docker stop react-app

      - name: Build Node.js Backend
        run: |
          docker build -t node-backend ./app/backend/node

      - name: Test Run Node.js Backend
        run: |
          docker run -d --name node-app -p 5000:5000 node-backend
          sleep 5  
          # Perform tests here, e.g., curl localhost:5000/api
          docker stop node-app

      - name: Build Python Backend
        run: |
          docker build -t python-backend ./app/backend/python

      - name: Test Run Python Backend
        run: |
          docker run -d --name python-app -p 5001:5001 python-backend
          sleep 5 
          # Perform tests here, e.g., curl localhost:5001/api
          docker stop python-app
